name: Format

on:
  push:
    branches:
      - master
      - develop
      - chrysalis-2
      - feat/actions-test-all
  pull_request:
    branches:
      - master
      - develop
      - chrysalis-2
    paths-ignore:
      - "docs/**"
      - "specification/**"

jobs:
  format:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        project:
          [
            "iota-streams-core",
            "iota-streams-core-edsig",
            "iota-streams-core-keccak",
            "iota-streams-ddml",
            "iota-streams-app",
            "iota-streams-app-channels",
            "iota-streams-app-channels-example",
            "examples",
            "bindings/c",
            "bindings/wasm",
          ]

    steps:
      - uses: actions/checkout@v2
      - name: Install rustfmt with nightly toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
          components: rustfmt
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --manifest-path=${{ matrix.project }}/Cargo.toml --all -- --check
